### ISSUE TITLE
存在crash风险

### ISSUE THREAD

**Issue by zhangfurun** [tangdiforx/TTAVPlayer#1]
当视频处于加载状态,还未处于播放状态,如果拖动slider,会出现崩溃

给出的建议:
在初始加载的状态,下部状态栏不显示
或者
修改相关的bug

**Comment by tangdiforx** [comment]
多谢你提出这个问题！我已经修复了这个问题，在播放器尚未加载完毕之前，滑动条不能拖动。

新增两个API:
//播放器加载完毕前的预处理
- (void)beforePlayerLoadPretreatment

//播放器加载完毕之后的处理,这部分逻辑不与播放方法耦合
- (void)afterPlayerLoadTreatment

如果还有未加载完毕前需要做处理的，都可以放在这。
