### ISSUE TITLE
可否具体写一下集成方式

### ISSUE THREAD

**Issue by Eddiegooo** [tangdiforx/TTAVPlayer#2]
手动集成 和 是pods集成方式，  我直接拖文件夹TTAVPlayer到项目中，手动集成，运行不了。可否具体完善下集成方式。O(∩_∩)O谢谢

**Comment by tangdiforx** [comment]
你好，我暂时还并未上传到pods源里。如果你需要pods集成方式的话，可否新开一个issue，我专门跟进。手动集成的话需要将TTAVPlayer.framework直接链接进你的主项目，同时需要按照Target标分别编译成X86,i386结构的framework和arm结构的framework，然后使用lipo -create合成一个通用的framework。这样会稍微麻烦一点，我还是尽快弄成pods方式吧，周末搞定，留个联系方式我通知你~

**Comment by Eddiegooo** [comment]
@tangdiforx 我是渣渣。 手动集成没搞定。。 我是将文件夹TTAVPlayer 和 TTAVPlayer.framework拖到项目中。  关联了framework 还是不可以呢。
我们项目没用pods，都是手动集成的。

**Comment by tangdiforx** [comment]
@Eddiegooo 你是不是提示x86_64 undefined symbol或者是arm64 undefined symbol？

**Comment by Eddiegooo** [comment]
@tangdiforx  不是  是引入的问题    TTAVplayer文件夹 好多东西与项目中是冲突的
可以了 好开心  O(∩_∩)O谢谢

**Comment by tangdiforx** [comment]
@Eddiegooo 噗，这样。TTAVPlayer文件夹里的是源码，只是让你们看的啦~。我现在有些忙，等我闲下来把集成过程和pods搞定。

**Comment by Eddiegooo** [comment]
@tangdiforx  嗯嗯 好 你先忙  我再自己看看   
demo里可以了，拖到工程里又不行了 醉了醉了。
等你完善好集成方式 我再加到项目中吧，搞不定了。报错这个：
![2017-06-09 3 57 41](https://user-images.githubusercontent.com/10209529/26966385-68949006-4d2c-11e7-94ae-b030b931460d.png)

nmgfqlong@126.com

**Comment by tangdiforx** [comment]
抱歉，我刚刚试了一下，发现原来TTAVPlayer是默认的动态库。我刚刚已经改掉了。自己测了一下在第三方中已经集成OK。

具体的集成方式我会在周末写完~

**Comment by Eddiegooo** [comment]
@tangdiforx   好的 辛苦了 我在看看  再次感谢
